package me.limeth.storageAPI;

public enum ColumnType
{
	BOOLEAN, TINYINT, SMALLINT, MEDIUMINT, INT, BIGINT, FLOAT, DOUBLE, DECIMAL, DATE, DATETIME, TIMESTAMP, TIME, YEAR, CHAR, VARCHAR, TINYBLOB, BLOB, MEDIUMBLOB, LONGBLOB, ENUM, SET;
}
